export const TOKEN_TO_STORE = "TOKEN_TO_STORE";

export const USER_INIT_SUCCESS = "USER_INIT_SUCCESS";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const CARBRAND_SET_CARBRANDS="CARBRAND_SET_CARBRANDS";
export const CARBRAND_SET_CARBRAND="CARBRAND_SET_CARBRAND";
export const CARBRAND_REMOVE_CARBRAND="CARBRAND_REMOVE_CARBRAND";
export const CARBRAND_SET_EDITORINPUT="CARBRAND_SET_EDITORINPUT";

export const NOTIFICATIONSETTING_SET_NOTIFICATIONSETTINGS="NOTIFICATIONSETTING_SET_NOTIFICATIONSETTINGS";